version: 2
updates:
  - directory: /
    labels:
      - dependencies
    package-ecosystem: npm
    reviewers:
      - sailwebs
    assignees:
      - sailwebs
    schedule:
      # The Dependabot does not support Yarn berry,
      # so lower priority as an interim measure.
      interval: monthly