apiVersion: apps.kubeblocks.io/v1alpha1
kind: Cluster
metadata:
  name: redis
spec:
  affinity:
    podAntiAffinity: Preferred
    tenancy: SharedNode
    topologyKeys:
    - kubernetes.io/hostname
  clusterDefinitionRef: redis
  clusterVersionRef: redis-7.0.6
  componentSpecs:
  - componentDef: redis
    enabledLogs:
    - running
    monitor: false
    name: redis
    replicas: 2
    resources:
      limits:
        cpu: "2"
        memory: 1Gi
      requests:
        cpu: "2"
        memory: 1Gi
    switchPolicy:
      type: Noop
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  - componentDef: redis-sentinel
    name: redis-sentinel
    replicas: 3
    resources:
      limits:
        cpu: "0.2"
        memory: 0.2Gi
      requests:
        cpu: "0.2"
        memory: 0.2Gi
    volumeClaimTemplates:
    - name: data
      spec:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 20Gi
  terminationPolicy: Delete
