name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
    # Review gh actions docs if you want to further define triggers, paths, etc
    # https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#on

env:
  GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Kubeblocks.io
        uses: actions/checkout@v3

      - name: Checkout Kubeblocks Docs main
        uses: actions/checkout@v3
        with: 
           repository: apecloud/kubeblocks
           ref: main
           path: ".temp/main"
           token: ${{ env.GITHUB_TOKEN }}

      # - name: Checkout Kubeblocks Docs release-0.3
      #   uses: actions/checkout@v3
      #   with: 
      #      repository: apecloud/kubeblocks
      #      ref: release-0.3
      #      path: ".temp/release-0.3"
      #      token: ${{ env.GITHUB_TOKEN }}

      # - name: Checkout Kubeblocks Docs release-0.4
      #   uses: actions/checkout@v3
      #   with: 
      #      repository: apecloud/kubeblocks
      #      ref: release-0.4
      #      path: ".temp/release-0.4"
      #      token: ${{ env.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Reset Docs
        run: yarn docs:reset

      - name: Install Dependencies
        run: yarn install --frozen-lockfile

      - name: Build Docs
        run: yarn build

      # Popular action to deploy to GitHub Pages:
      # Docs: https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-docusaurus
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # Build output to publish to the `gh-pages` branch:
          publish_dir: ./build
          # The following lines assign commit authorship to the official
          # GH-Actions bot for deploys to `gh-pages` branch:
          # https://github.com/actions/checkout/issues/13#issuecomment-724415212
          # The GH actions bot is used by default if you didn't specify the two fields.
          # You can swap them out with your own user credentials.
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com